# Generated by Django 3.2.8 on 2021-11-09 04:23

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.FileField(upload_to='tracks', validators=[users.validators.validate_is_audio]),
        ),
    ]
