# Generated by Django 3.2.8 on 2021-11-11 01:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20211110_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='track_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
