# Generated by Django 3.2.8 on 2021-11-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211111_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='liked',
            new_name='likes',
        ),
        migrations.AddField(
            model_name='track',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
